# Generated by Django 3.2 on 2021-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbills', '0003_alter_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=None),
        ),
    ]
