# Generated by Django 3.2 on 2021-04-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbills', '0004_alter_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
