# Generated by Django 3.2 on 2021-05-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addbills', '0005_auto_20210429_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
    ]
